### ISSUE TITLE
[BUG] typo in m2l_geometry

### ISSUE THREAD

**Issue by markjessell** [Loop3D/map2loop-2#98]
### Describe your issue

crashes in m2l_geometry:

line 273

agroup = apoint["GROUP"]

should be (I think)

agroup = apoly["GROUP"]

### Minimal reproducing code example

```python
changing to             agroup = apoly["GROUP"]

seems to fix it...
```

### Error message

```shell
Traceback (most recent call last):
  File "Run_test.py", line 39, in <module>
    proj.run()
  File "/home/mark/anaconda3/envs/loop/lib/python3.8/site-packages/map2loop/m2l_utils.py", line 1400, in clean
    return func(*args, **kwargs)
  File "/home/mark/anaconda3/envs/loop/lib/python3.8/site-packages/map2loop/project.py", line 563, in run
    self.map_data.export_orientations(self.workflow)
  File "<@beartype(map2loop.mapdata.MapData.export_orientations) at 0x7f5609422280>", line 31, in export_orientations
  File "/home/mark/anaconda3/envs/loop/lib/python3.8/site-packages/map2loop/mapdata.py", line 674, in export_orientations
    m2l_geometry.create_orientations(self.config, self, workflow)
  File "<@beartype(map2loop.m2l_geometry.create_orientations) at 0x7f56091f6ee0>", line 71, in create_orientations
  File "/home/mark/anaconda3/envs/loop/lib/python3.8/site-packages/map2loop/m2l_geometry.py", line 273, in create_orientations
    agroup = apoint["GROUP"]
UnboundLocalError: local variable 'apoint' referenced before assignment
```

**Comment by RoyThomsonMonash** [comment]
Bug fixed in newest release
